### PR TITLE
Refactor/fix lint and formatting

### PR DESCRIPTION
**Pull request by yellowHatpro**
- Refactored whole code base using 
    - `cargo fmt`
    - clippy
- Added pre commit config that generates hook which checks for formatting before committing changes

### CODE REVIEW

**Comment by yellowHatpro** [comment]
Nothing breaks so merging

**Comment by RustyNova016** [comment]
IMO reformating shouldn't rely solely on pre commit. There should also be CI in place to prevent merging non reformated  (or even code with warnings) in the first place. 

If someone start contributing without having pre commits installed, they may push non formatted code to the codebase, that could accidentally be merged in the main branch

**Comment by yellowHatpro** [comment]
> IMO reformating shouldn't rely solely on pre commit. There should also be CI in place to prevent merging non reformated (or even code with warnings) in the first place.
> 
> If someone start contributing without having pre commits installed, they may push non formatted code to the codebase, that could accidentally be merged in the main branch

Yup, it was intentional. I wanted to create another PR for CI purpose, this one was specially for lints and re formatting of whole codebase.
CI will have other steps as well, like tests. 
Moreover, I had written instructions to setup precommit in local inside the .pre-commit-config.yaml file, but ig I should also mention in docs as well.

**Comment by RustyNova016** [comment]
I don't really like using pre-commit so yeah, it will be better. 
Sometimes I just want to commit 'n push, without caring if the code is fine. Then when I'm ready to merge I do the fmt and clippy, and rebase squash until everything is pretty

**Comment by yellowHatpro** [comment]
Oh, I think you can pass `--no-verify` flag in those situations. It will skip the pre-commit hook for the commit.

**Pull request merged**
